### PR TITLE
Fix compatibility with ramsey/uuid:^4.1

### PR DESCRIPTION
**Pull request by caiquecastro**

### CODE REVIEW

**Comment by caiquecastro** [comment]
Needs to change on dyrynda/laravel-efficient-uuid package:

image

**Comment by caiquecastro** [comment]
Probably fix #93

**Comment by michaeldyrynda** [comment]
I don't think this will preserve functionality, though, as you're just resolving implicitly from string or bytes, rather than a specific version.

**Comment by michaeldyrynda** [comment]
That said, I don't think you can really use UUID versions 2, 3, or 5 anyway, as they require additional parameters be passed anyway.

**Comment by michaeldyrynda** [comment]
Fixed in b273499c41f62a8601a385f1652ba5ee584b0a5f

**Comment by ziming** [comment]
@michaeldyrynda 

If 'ordered' is now pipe through uuid 6, will it have any conflicts or issues with my previous uuids that are already generated with Str::orderedUuid() ?

https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Str.php#L693

Hopefully you know the answer, thank you.

**Comment by michaeldyrynda** [comment]
It _may_ be possible, given that the ordered UUID does not appear to actually be a proper [time-ordered UUID](https://github.com/laravel/framework/commit/3d39604bba72d45dab5b53951af42bbb21110cad#commitcomment-28371947). 

It may be worth considering updating the UUID to use the new format which forms a truer representation of an ordered UUID, albeit from a [draft specification](https://github.com/uuid6/uuid6-ietf-draft).

**Comment by ziming** [comment]
Noted the potential breaking changes, shall restrict ramsey uuid to 4.1 for the time being then.

**Pull request closed without merging**
