### PR TITLE
Compatibility for 5.5

### PR DESCRIPTION
**Pull request by jpmurray**
Hello,

This is just updating illuminate dependencies for 5.5. I've been using my fork for a little while now, everything just works fine.

**Important**: I had to remove the minimum stability flag to use with 5.5 at the moment, because it's still on dev. I guess you might want to wait until release to merge this and keep the stable flag?

### CODE REVIEW

**Comment by michaeldyrynda** [comment]
Hey @jpmurray, thanks for this!

I'll update once 5.5 is released next week.

**Comment by fwartner** [comment]
This is already 19 days ago and Laravel is still not on 5.5 😆 
Any updates on this?

**Comment by michaeldyrynda** [comment]
It won't work without a 5.5 tag anyway, no? In any case, 5.5 ought to be out by the end of the month. Haven't forgotten, have it in todoist for end of month at latest :)

**Comment by fwartner** [comment]
I haven´t tried yet. But will do. :)

**Comment by jpmurray** [comment]
Take to pressure for it. I've been using my fork since the day I opened the PR, it works flawlessly, just merge it when the release comes! ;-)

**Comment by fwartner** [comment]
Great to read that!

**Comment by michaeldyrynda** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpmurray** [comment]
🎉

**Pull request merged**
