### PR TITLE
feat: uuid v7 support

### PR DESCRIPTION
**Pull request by atymic**
- added support for v7 uuids
- added tests to cover v7 uuids

### CODE REVIEW

**Comment by atymic** [comment]
@michaeldyrynda thoughts? :)

**Comment by atymic** [comment]
Can also add ULIDs

**Comment by michaeldyrynda** [comment]
I don't know how I missed this for... 4 months @atymic 

Have just merged; will tag shortly!

**Comment by michaeldyrynda** [comment]
Merged in 81976f5

**Pull request closed without merging**
